services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql-dbase
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
      - ./config/mysql/conf-local:/etc/mysql/conf.d:cached

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db